### ISSUE TITLE
Inquiry 

### ISSUE THREAD

**Issue by TeamDy** [thisdotvoid/adjaranet-android-client#12]
Hello Sir,

I am Pankaj. I have modified this code and build my own app but I have one question in my mind suppose if I want to publish my this app on Google playstore then which legal justification I need to provide them. Please tell me sir.

Thank you.

**Comment by thisdotvoid** [comment]
I don't know, Google rejected this app because it violates the unauthorized use of copyrighted content policy. You can't do much if you are showing pirated movies.

**Comment by TeamDy** [comment]
oh, okay.
Thank you sir.

**Comment by lagadpankaj** [comment]
Hello Sir, 

Today I have saw you have updated your GPL-v3 license for this code. So now can we legally publish this app on play store? 

Please reply soon..

Thank you.
