### ISSUE TITLE
I cannot search any movies now in this app.. Previously it was working. Why?

### ISSUE THREAD

**Issue by lagadpankaj** [thisdotvoid/adjaranet-android-client#17]
On my Oppo A83..I cannot search any movies now in this app.. Previously it was working. What is the problem?

**Comment by thisdotvoid** [comment]
because api was changed, fixed in https://github.com/thisdotvoid/adjaranet-android-client/commit/bd5e33589378b9ba86a06bf6947f25506b8167ff

**Comment by lagadpankaj** [comment]
Thanks my dear :+1:
