### ISSUE TITLE
Not fetching movie data of related movies also video player library version is very old. PercentRelativeLayout is deprecated. :) 

### ISSUE THREAD

**Issue by lagadpankaj** [thisdotvoid/adjaranet-android-client#7]

**Comment by thisdotvoid** [comment]
@lagadpankaj will see if I have time for that, thanks

**Comment by lagadpankaj** [comment]
Okay dear kindly update it. I would like to learn something new from you :)

**Comment by thisdotvoid** [comment]
PercentRelativeLayout issue is tracked with #8, others are fixed.
