### ISSUE TITLE
PercentRelativeLayout is deprecated. How to replace and configure PercentRelativeLayout with ConstraintLayout?

### ISSUE THREAD

**Issue by TeamDy** [thisdotvoid/adjaranet-android-client#8]
PercentRelativeLayout is deprecated. How to replace and configure PercentRelativeLayout with ConstraintLayout? Please solve this problem for me I'm working on this problem but didn't found any solution.

Here is deprecated code : 

private void adjustVideoViewSize() {
        PercentRelativeLayout.LayoutParams params = (PercentRelativeLayout.LayoutParams) mVideoView.getLayoutParams();
        PercentLayoutHelper.PercentLayoutInfo info = params.getPercentLayoutInfo();
        info.heightPercent = isFullscreen ? 1f : 0.35f;
        mVideoView.requestLayout();
    }

**Comment by thisdotvoid** [comment]
Tracked with #11
